<template>
  <a-modal
    :visible="visible"
    title="Add New Project"
    okText="Add Project"
    cancelText="Cancel"
    @cancel="handleCancel"
    @ok="handleSubmit"
    :confirmLoading="isSubmitting"
  >
    <a-form ref="formRef" :model="formState" layout="vertical" name="project_form">
      <a-form-item
        name="name"
        label="Project Name"
        :rules="[{ required: true, message: 'Please input the name of the project!' }]"
      >
        <a-input v-model:value="formState.name" />
      </a-form-item>
      <!-- Optional: Project color, parent project, etc. can be added later -->
    </a-form>
  </a-modal>
</template>

<script setup>
import { ref, reactive, defineProps, defineEmits } from 'vue';
import { useProjectsStore } from '@/store/projectsStore';
import { Modal as AModal, Form as AForm, FormItem as AFormItem, Input as AInput } from 'ant-design-vue';

const props = defineProps({
  visible: { type: Boolean, required: true },
});

const emit = defineEmits(['close', 'projectAdded']);

const projectsStore = useProjectsStore();
const formRef = ref();
const isSubmitting = ref(false);

const formState = reactive({
  name: '',
});

const handleCancel = () => {
  formRef.value.resetFields();
  emit('close');
};

const handleSubmit = async () => {
  try {
    await formRef.value.validate();
    isSubmitting.value = true;
    const newProject = {
      // id will be generated by the store or a utility function
      name: formState.name,
    };
    projectsStore.addProject(newProject); // The store action should handle ID generation

    isSubmitting.value = false;
    emit('projectAdded'); // Optionally pass the new project
    handleCancel(); // Close and reset form
  } catch (errorInfo) {
    console.log('Validation Failed:', errorInfo);
    isSubmitting.value = false;
  }
};
</script>
