package com.example.cameraecommerce.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * <p>
 * 购物车项表
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:05:00Z
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("t_cart_item")
public class CartItem implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 购物车项ID，主键
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 用户ID
     */
    @TableField("user_id")
    private Long userId;

    /**
     * 商品ID
     */
    @TableField("product_id")
    private Long productId;

    /**
     * 商品数量
     */
    @TableField("quantity")
    private Integer quantity;

    /**
     * 加入购物车时的商品单价 (冗余字段，可选)
     */
    @TableField("price_at_addition")
    private BigDecimal priceAtAddition;

    /**
     * 是否选中用于结算: 0-未选中, 1-已选中
     */
    @TableField("checked_status")
    private Integer checkedStatus;


    /**
     * 创建时间
     */
    @TableField("created_at")
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    @TableField("updated_at")
    private LocalDateTime updatedAt;

    // --- 非数据库表字段，用于业务逻辑 ---
    /**
     * 商品名称 (VO属性，需要联查填充)
     */
    @TableField(exist = false)
    private String productName;

    /**
     * 商品主图 (VO属性，需要联查填充)
     */
    @TableField(exist = false)
    private String productMainImage;

    /**
     * 商品当前价格 (VO属性，需要联查填充)
     */
    @TableField(exist = false)
    private BigDecimal currentPrice;

    /**
     * 商品当前库存 (VO属性，需要联查填充)
     */
    @TableField(exist = false)
    private Integer currentStock;


}
