package com.example.cameraecommerce.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * <p>
 * 订单项表
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:04:00Z
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("t_order_item")
public class OrderItem implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 订单项ID，主键
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 订单ID
     */
    @TableField("order_id")
    private Long orderId;

    /**
     * 订单编号 (冗余)
     */
    @TableField("order_sn")
    private String orderSn;

    /**
     * 商品ID
     */
    @TableField("product_id")
    private Long productId;

    /**
     * 商品名称 (冗余)
     */
    @TableField("product_name")
    private String productName;

    /**
     * 商品SKU (冗余, 可选)
     */
    @TableField("product_sku")
    private String productSku;

    /**
     * 商品图片URL (冗余)
     */
    @TableField("product_image_url")
    private String productImageUrl;

    /**
     * 购买数量
     */
    @TableField("quantity")
    private Integer quantity;

    /**
     * 商品单价 (成交时价格)
     */
    @TableField("unit_price")
    private BigDecimal unitPrice;

    /**
     * 该项总价
     */
    @TableField("total_price")
    private BigDecimal totalPrice;

    /**
     * 创建时间
     */
    @TableField("created_at")
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    @TableField("updated_at")
    private LocalDateTime updatedAt;

}
