package com.example.cameraecommerce.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * <p>
 * 订单表
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:03:00Z
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("t_order")
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 订单ID，主键
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 订单编号，唯一
     */
    @TableField("order_sn")
    private String orderSn;

    /**
     * 用户ID
     */
    @TableField("user_id")
    private Long userId;

    /**
     * 订单总金额
     */
    @TableField("total_amount")
    private BigDecimal totalAmount;

    /**
     * 应付金额 (可能经过促销折扣)
     */
    @TableField("payable_amount")
    private BigDecimal payableAmount;

    /**
     * 支付方式: 1-模拟支付宝, 2-模拟微信支付等
     */
    @TableField("payment_method")
    private Integer paymentMethod;

    /**
     * 支付状态: 0-未支付, 1-已支付, 2-支付失败, 3-已退款
     */
    @TableField("payment_status")
    private Integer paymentStatus;

    /**
     * 支付时间
     */
    @TableField("payment_time")
    private LocalDateTime paymentTime;

    /**
     * 发货状态: 0-未发货, 1-已发货, 2-已签收
     */
    @TableField("shipping_status")
    private Integer shippingStatus;

    /**
     * 发货时间
     */
    @TableField("shipping_time")
    private LocalDateTime shippingTime;

    /**
     * 确认收货时间
     */
    @TableField("receive_time")
    private LocalDateTime receiveTime;

    /**
     * 订单状态: 0-待付款, 1-待发货, 2-已发货, 3-已完成, 4-已关闭(取消/超时), 5-售后中
     */
    @TableField("order_status")
    private Integer orderStatus;

    /**
     * 收货人姓名
     */
    @TableField("receiver_name")
    private String receiverName;

    /**
     * 收货人电话
     */
    @TableField("receiver_phone")
    private String receiverPhone;

    /**
     * 收货详细地址
     */
    @TableField("receiver_address")
    private String receiverAddress;

    /**
     * 运费
     */
    @TableField("shipping_fee")
    private BigDecimal shippingFee;

    /**
     * 促销活动信息
     */
    @TableField("promotion_info")
    private String promotionInfo;

    /**
     * 发票抬头
     */
    @TableField("invoice_header")
    private String invoiceHeader;

    /**
     * 订单备注
     */
    @TableField("remarks")
    private String remarks;

    /**
     * 创建时间
     */
    @TableField("created_at")
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    @TableField("updated_at")
    private LocalDateTime updatedAt;

}
