package com.example.cameraecommerce.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * <p>
 * 商品表
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:02:00Z
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("t_product")
public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 商品ID，主键
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * 分类ID
     */
    @TableField("category_id")
    private Long categoryId;

    /**
     * 商品名称
     */
    @TableField("name")
    private String name;

    /**
     * 副标题/简短描述
     */
    @TableField("subtitle")
    private String subtitle;

    /**
     * 商品详细描述
     */
    @TableField("description")
    private String description;

    /**
     * 商品SKU，唯一（可选）
     */
    @TableField("sku")
    private String sku;

    /**
     * 商品原价
     */
    @TableField("price")
    private BigDecimal price;

    /**
     * 商品折扣价 (促销应用后)
     */
    @TableField("discount_price")
    private BigDecimal discountPrice;

    /**
     * 库存数量
     */
    @TableField("stock")
    private Integer stock;

    /**
     * 主图片URL
     */
    @TableField("main_image_url")
    private String mainImageUrl;

    /**
     * 其他图片URL列表 (JSON格式或逗号分隔)
     */
    @TableField("image_urls")
    private String imageUrls; // 存储为TEXT，通常是JSON字符串

    /**
     * 商品状态: 0-下架, 1-上架, 2-预售等
     */
    @TableField("status")
    private Integer status;

    /**
     * 商品标签 (逗号分隔)
     */
    @TableField("tags")
    private String tags;

    /**
     * 品牌
     */
    @TableField("brand")
    private String brand;

    /**
     * 型号
     */
    @TableField("model_number")
    private String modelNumber;

    /**
     * 浏览次数
     */
    @TableField("view_count")
    private Integer viewCount;

    /**
     * 销量
     */
    @TableField("sale_count")
    private Integer saleCount;

    /**
     * 创建时间
     */
    @TableField("created_at")
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    @TableField("updated_at")
    private LocalDateTime updatedAt;

}
