package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.CartItem;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
// import org.apache.ibatis.annotations.Param;
// import java.util.List;

/**
 * <p>
 * 购物车项表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:13:00Z
 */
@Mapper
public interface CartItemMapper extends BaseMapper<CartItem> {
    // 如果 CartItem 实体包含了VO属性，可能需要自定义查询来填充这些属性
    // 例如:
    // List<CartItem> selectCartItemsWithProductDetails(@Param("userId") Long userId);
}
