package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.Order;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * <p>
 * 订单表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:14:00Z
 */
@Mapper
public interface OrderMapper extends BaseMapper<Order> {

}
