package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.OrderItem;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
// import java.util.List;

/**
 * <p>
 * 订单项表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:15:00Z
 */
@Mapper
public interface OrderItemMapper extends BaseMapper<OrderItem> {
    // int insertBatch(@Param("orderItems") List<OrderItem> orderItems); // 批量插入订单项
}
