package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.Product;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * <p>
 * 商品表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:12:00Z
 */
@Mapper
public interface ProductMapper extends BaseMapper<Product> {
    // 可以在此定义复杂查询方法，对应的SQL写在 ProductMapper.xml (如果需要)
    // 例如：扣减库存
    // int decreaseStock(@Param("productId") Long productId, @Param("quantity") Integer quantity);
}
