package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.ProductCategory;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * <p>
 * 商品分类表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:11:00Z
 */
@Mapper
public interface ProductCategoryMapper extends BaseMapper<ProductCategory> {

}
