package com.example.cameraecommerce.mapper;

import com.example.cameraecommerce.entity.User;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * <p>
 * 用户表 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2023-12-15T10:10:00Z
 */
@Mapper
public interface UserMapper extends BaseMapper<User> {

}
